### ISSUE TITLE
Can't connect to wallet on Mobile

### ISSUE THREAD

**Issue by timfam** [kjmczk/nextjs-nft-mint-dapp#10]
On mobile connection button does not work.

**Comment by timfam** [comment]
Mobile metamask not working on chrome android browser. "please install metamask" when you click connect button

**Comment by kjmczk** [comment]
Replace `setErrorMessage('Please install MetaMask.');` with `window.open ('https://metamask.app.link/dapp/www.yourdomain.com', '_ blank');` in `components/ConnectButton.tsx`.

And replace the "www.yourdomain.com" part with your domain.

**Comment by timfam** [comment]
Issue resolved
