### ISSUE TITLE
Mint button not working

### ISSUE THREAD

**Issue by unfairDude** [kjmczk/nextjs-nft-mint-dapp#12]
hi, trying your dapp right now on development mode with mumbai network.
evrything built fine, but the mint button just dont work. any idea on how to fix the issue?
I used remix for deployment and abi

edit tried deploying also on vercel, same issue. 

this is the contract that im using:

//SPDX-License-Identifier: MIT

pragma solidity ^0.8.7;

import "contracts/token/ERC721/extensions/ERC721Enumerable.sol";
import "contracts/access/Ownable.sol";

contract TheStripesNFT is ERC721Enumerable, Ownable {
    using Strings for uint256;

    string public baseURI;
    string public baseExtension = ".json";
    uint256 public cost = 0.002471 ether;
    uint256 public presaleCost = 0.002471 ether;
    uint256 public maxSupply = 5000;
    uint256 public maxMintAmount = 10;
    bool public paused = false;
    mapping(address => bool) public whitelisted;
    mapping(address => bool) public presaleWallets;

    constructor(
        string memory _name,
        string memory _symbol,
        string memory _initBaseURI
    ) ERC721(_name, _symbol) {
        setBaseURI(_initBaseURI);
    }

    // internal
    function _baseURI() internal view virtual override returns (string memory) {
        return baseURI;
    }

    // public
    function mint(address _to, uint256 _mintAmount) public payable {
        uint256 supply = totalSupply();
        require(!paused);
        require(_mintAmount > 0);
        require(_mintAmount <= maxMintAmount);
        require(supply + _mintAmount <= maxSupply);

        if (msg.sender != owner()) {
            if (whitelisted[msg.sender] != true) {
                if (presaleWallets[msg.sender] != true) {
                    //general public
                    require(msg.value >= cost * _mintAmount);
                } else {
                    //presale
                    require(msg.value >= presaleCost * _mintAmount);
                }
            }
        }

        for (uint256 i = 1; i <= _mintAmount; i++) {
            _safeMint(_to, supply + i);
        }
    }

    function walletOfOwner(address _owner)
        public
        view
        returns (uint256[] memory)
    {
        uint256 ownerTokenCount = balanceOf(_owner);
        uint256[] memory tokenIds = new uint256[](ownerTokenCount);
        for (uint256 i; i < ownerTokenCount; i++) {
            tokenIds[i] = tokenOfOwnerByIndex(_owner, i);
        }
        return tokenIds;
    }

    function tokenURI(uint256 tokenId)
        public
        view
        virtual
        override
        returns (string memory)
    {
        require(
            _exists(tokenId),
            "ERC721Metadata: URI query for nonexistent token"
        );

        string memory currentBaseURI = _baseURI();
        return
            bytes(currentBaseURI).length > 0
                ? string(
                    abi.encodePacked(
                        currentBaseURI,
                        tokenId.toString(),
                        baseExtension
                    )
                )
                : "";
    }

    //only owner
    function setCost(uint256 _newCost) public onlyOwner {
        cost = _newCost;
    }

    function setPresaleCost(uint256 _newCost) public onlyOwner {
        presaleCost = _newCost;
    }

    function setmaxMintAmount(uint256 _newmaxMintAmount) public onlyOwner {
        maxMintAmount = _newmaxMintAmount;
    }

    function setBaseURI(string memory _newBaseURI) public onlyOwner {
        baseURI = _newBaseURI;
    }

    function setBaseExtension(string memory _newBaseExtension)
        public
        onlyOwner
    {
        baseExtension = _newBaseExtension;
    }

    function pause(bool _state) public onlyOwner {
        paused = _state;
    }

    function whitelistUser(address _user) public onlyOwner {
        whitelisted[_user] = true;
    }

    function removeWhitelistUser(address _user) public onlyOwner {
        whitelisted[_user] = false;
    }

    function addPresaleUser(address _user) public onlyOwner {
        presaleWallets[_user] = true;
    }

    function add100PresaleUsers(address[100] memory _users) public onlyOwner {
        for (uint256 i = 0; i < 2; i++) {
            presaleWallets[_users[i]] = true;
        }
    }

    function removePresaleUser(address _user) public onlyOwner {
        presaleWallets[_user] = false;
    }

    function withdraw() public payable onlyOwner {
        (bool success, ) = payable(msg.sender).call{
            value: address(this).balance
        }("");
        require(success);
    }
}

**Comment by kjmczk** [comment]
Hi. The `mint` function in your smart contract has `address _to` as its first argument, so you need to specify `address` when calling the function in your dApp.
```ts
// components/Minting.tsx
async function mintNFTs() {
  // ...
    const transaction = await contract.mint(address, mintAmount, {
      value: totalWei,
    });
  // ...
}
```

**Comment by unfairDude** [comment]
> Hi. The `mint` function in your smart contract has `address _to` as its first argument, so you need to specify `address` when calling the function in your dApp.
> 
> ```ts
> // components/Minting.tsx
> async function mintNFTs() {
>   // ...
>     const transaction = await contract.mint(address, mintAmount, {
>       value: totalWei,
>     });
>   // ...
> }
> ```

thanks for the reply, I will try like you suggested

**Comment by unfairDude** [comment]
> ```ts
> // ...i
> ```

Hi, thanks for the reply, I modified that line of code with your, but the mint button still not prompting any transaction. What am I doing wrong?

**Comment by kjmczk** [comment]
Sorry, replace "address" with "account".
```ts
// components/Minting.tsx
async function mintNFTs() {
  // ...
    const transaction = await contract.mint(account, mintAmount, {
      value: totalWei,
    });
  // ...
}
```

**Comment by unfairDude** [comment]
> Sorry, replace "address" with "account".
> 
> ```ts
> // components/Minting.tsx
> async function mintNFTs() {
>   // ...
>     const transaction = await contract.mint(account, mintAmount, {
>       value: totalWei,
>     });
>   // ...
> }
> ```


Omg man, thanks. It worked perfectly.
Really appreciate
