### ISSUE TITLE
Need help ASAP

### ISSUE THREAD

**Issue by cankaytaz** [kjmczk/nextjs-nft-mint-dapp#15]
Hi, When I start dev server always getting same fail. Can you help me with that. 
<img width="958" alt="Ekran Resmi 2022-07-14 17 43 21" src="https://user-images.githubusercontent.com/12648146/179010233-b5c5878c-9a48-4976-9896-3bc5ef3fe53a.png">
<img width="964" alt="Ekran Resmi 2022-07-14 17 43 37" src="https://user-images.githubusercontent.com/12648146/179010260-566aee5d-9687-4b38-862d-d724a6245c5e.png">

**Comment by kjmczk** [comment]
Hi. It looks like your dApp isn't interacting properly with your smart contract. Let me know about your backend. Are you using a backend ([Hardhat NFT Smart Contract](https://github.com/kjmczk/hardhat-nft-smart-contract)) I created, or your own smart contract? Are you running on localhost, or Testnet (Rinkeby etc.)?

**Comment by prasannathapa10** [comment]
I am getting same problem, I used the contract recommended by you and using rinkeby testnet. I install every dependecies still getting same problem. 
![image](https://user-images.githubusercontent.com/29574777/179871247-f9c6c8a2-a4a6-4a38-a4eb-07438d37b75a.png)

**Comment by kjmczk** [comment]
1 . Did you deploy your contract by running the following command on the backend? :

```sh
npx hardhat deploy --network rinkeby
```

2 . Is the data from the backend reflected in the frontend `contract-config.json` and `abi.json` files?:

`contract-config.json`:

```json
{
  "contractAddresses": {
    "1": [],
    "4": ["0x..."],
    "1337": []
  },
}
```

`abi.json`:

```json
[
  {
    "type": "constructor",
    "payable": false,
    "inputs": [
      { "type": "string", "name": "nftName" },
      { "type": "string", "name": "nftSymbol" },
      { "type": "string", "name": "hiddenMetadataUri" },
      { "type": "uint256", "name": "maxSupply" },
      { "type": "uint256", "name": "mintPrice" },
      { "type": "uint256", "name": "maxMintAmountPerTx" }
    ]
  },
  ...
]
```

3 . If you have deployed your contract but these data are not reflected in the frontend, make sure the paths in the backend `project-config.ts` file match yours.

**Comment by biasaurs** [comment]
I am deploying the dapp using an allready deployed contract on mainnet, put in contract address & ABI still it tells me to connect to rinkeby! can you please help?

**Comment by kjmczk** [comment]
@biasaurs The message "Switch to Rinkeby Testnet" appears because you are using a development environment. Did you deploy your dApp to any hosting service? In a production environment, the `.env.production` file is used and you should not get that error.
