### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by kryptobaseddev** [kjmczk/nextjs-nft-mint-dapp#16]
I have googled to try and find a solution but still getting this error. I have enabled the .env files and I am trying to test a deployed contract I have. Not sure what else to change. Thank you for any guidance with this. I am still new in learning React. 

![image](https://user-images.githubusercontent.com/95310582/180321993-a07c5d19-2557-4a76-b39b-abf634f01219.png)

**Comment by kjmczk** [comment]
The error says that the environment variable is undefined, so it is not set or loaded. Check the following:

1. Environment files with the `.example` extension will not be loaded. Remove the `.example` extension. (Read the README)

2. If you change the value of the environment variable while the server is running, you need to restart the server.

**Comment by kryptobaseddev** [comment]
Thank you so much that was it, I modified the .env after server was running.
