### ISSUE TITLE
error - ./node_modules/@metamask/obs-store/dist/asStream.js:4:0

### ISSUE THREAD

**Issue by Inuzuka-Kiba** [kjmczk/nextjs-nft-mint-dapp#17]
Got this error when trying npm run dev and completely don't know what to do. I'm just a kid with a dream please help me kjmczk

btw your minting site is so cool ngl, Wish i can be a succesfull nft creator oneday but what can i do i only understand html and css lol
![Cuplikan layar 2022-07-24 192905](https://user-images.githubusercontent.com/109190777/180647092-120427d4-1e88-4d2c-9989-f55c73fbbbdd.png)

**Comment by kjmczk** [comment]
If you're not familiar with Node.js, JS/TS and React/Next.js, this dApp may be a challenge for you. First you need to learn about them, play with them, and get used to them. Alternatively, consider using a no-code tool or service.

Have you installed all the packages by running the `npm install` command? I can't identify the cause of the error, but if you follow the README, you shouldn't get the error.

**Comment by Inuzuka-Kiba** [comment]
> 

I did npm install and a little bit understand about packages and i already installed hardhat and deployed the smart contract and i also have edited env envdev and envproduction

**Comment by Inuzuka-Kiba** [comment]
> If you're not familiar with Node.js, JS/TS and React/Next.js, this dApp may be a challenge for you. First you need to learn about them, play with them, and get used to them. Alternatively, consider using a no-code tool or service.
> 
> Have you installed all the packages by running the `npm install` command? I can't identify the cause of the error, but if you follow the README, you shouldn't get the error.

Actually i have solved the problem but now i got another. When i have succesfully run npm run dev and open localhost:3000 on my chrome browser and connect my wallet to the site it can't detect that i'm in the correct network and keep showing please change to testnet cro (which i used for this experiment) How do i solve this?

**Comment by kjmczk** [comment]
If the chainId of the network you are connecting to your wallet matches the chainId in the environment file, you should not get the error. If you are using the Rinkeby testnet, the value of `NEXT_PUBLIC_CHAIN_ID` in the `.env.development` file must contain `4`. If you are using another testnet, set its chainId.

**Comment by Inuzuka-Kiba** [comment]
> If the chainId of the network you are connecting to your wallet matches the chainId in the environment file, you should not get the error. If you are using the Rinkeby testnet, the value of `NEXT_PUBLIC_CHAIN_ID` in the `.env.development` file must contain `4`. If you are using another testnet, set its chainId.

I put wrong chain id. My goodness, thank you so much sir

**Comment by kjmczk** [comment]
Great! This issue seems to have been resolved and will be closed.

**Comment by Inuzuka-Kiba** [comment]
> Great! This issue seems to have been resolved and will be closed.

Sure. btw, can you teach me how to make mint function in next js? I have created my own mint dapp with connect button using web3uikit but i don't know how to write the mint function.
