### ISSUE TITLE
Can't change from Rinkeby to Mainnet

### ISSUE THREAD

**Issue by biasaurs** [kjmczk/nextjs-nft-mint-dapp#18]
Hi I am trying this dapp using already deployed contract on etherscan. Put in ABI & contract address in the 1 ID, still it tells me to connect to rinkeby, when I change .env files, it gives an error.

**Comment by kjmczk** [comment]
@biasaurs The message "Switch to Rinkeby Testnet" appears because you are using a development environment. Did you deploy your dApp to any hosting service? In a production environment, the .env.production file is used and you should not get that error.

**Comment by biasaurs** [comment]
Application error: a client-side exception has occurred (see the browser console for more information).

**Comment by kjmczk** [comment]
As stated in the README, this dApp is designed for use with [hardhat-nft-smart-contract](https://github.com/kjmczk/hardhat-nft-smart-contract). So the function names of the contract are used in the dApp. You seem to be using your own contract, so you need to replace the contract functions in the dApp with yours.

**Comment by biasaurs** [comment]
thank you for help
