### ISSUE TITLE
Not an issue but i need your help to teach me write mint function for my dapp

### ISSUE THREAD

**Issue by Inuzuka-Kiba** [kjmczk/nextjs-nft-mint-dapp#19]
Can you help me? Please. I don't know what to do anymore. Only mint function i swear.

**Comment by Inuzuka-Kiba** [comment]
Everything is work just fine. But the mint button don't do anything because i don't know how to write mint function
![Cuplikan layar 2022-07-29 141953](https://user-images.githubusercontent.com/109190777/181705088-c9ad014d-4961-44c9-bdf4-047678696b24.png)
![Cuplikan layar 2022-07-29 141725](https://user-images.githubusercontent.com/109190777/181705123-f454f0d4-ed3e-404c-be14-5518420b7882.png)

**Comment by kjmczk** [comment]
A mint function must be defined in your smart contract. In your dApp, it's just called and executed. That's it because I'm not your mentor.

Please refrain from any personal questions that are not related to bugs or features of this app.

**Comment by Inuzuka-Kiba** [comment]
> A mint function must be defined in your smart contract. In your dApp, it's just called and executed. That's it because I'm not your mentor.
> 
> Please refrain from any personal questions that are not related to bugs or features of this app.

Tell me how to do that, How to called and execute the mint function.
