### ISSUE TITLE
Run Locally Error

### ISSUE THREAD

**Issue by souravmaji1** [kjmczk/nextjs-nft-mint-dapp#20]

**Comment by souravmaji1** [comment]
When i was trying to run the minting dapp by writing the command "npm run dev" i got this error can you solve this



![Capture](https://user-images.githubusercontent.com/87080195/183286113-eb28d763-9660-41b0-8f93-8a82deaa002a.PNG)

**Comment by kjmczk** [comment]
Did you run the `npm install` command? If you've done it and still get that error, I don't know why.
