### ISSUE TITLE
Fix suggestion for main Cover image not spanning correctly on larger screens

### ISSUE THREAD

**Issue by kryptobaseddev** [kjmczk/nextjs-nft-mint-dapp#21]
I noticed when testing, the image doesn't properly cover at top and aligns to the left when on larger screens. This isn't very apparent on smaller screens, but a simple update to the className wrapped around the Image can make it more responsive and span the page properly. I added this to the index.tsx in mine and it is working much smoother now

```
      <div className="w-full overflow-hidden">
      <Image src={topImage} alt={nftName} layout="responsive" />
      </div>
```

**Comment by kryptobaseddev** [comment]
The use of the `w-full` and `overflow-hidden` allows the image to span the entire top of the section no matter the screen size. The 'overflow-hidden' tag clips the image with no addition of scroll bars. Since using the 'w-full' it will stretch and keep the image resized so it won't actually clip fully. it really depends on the image dimension being used too, but I find it looks better when using both in conjunction. 

I am not a CSS guru by any means, but I have been studying the Tailwind css to try and see what works or doesn't. I have loved your setup for the Dapp and Contract, its nicely compartmentalized to allow for easy modification mostly, but some of the additional tweaks to the tailwind-config for themes could really help more too.

**Comment by kjmczk** [comment]
I see, thanks! I will update as you suggested.
