### ISSUE TITLE
Getting error when dapps run on licalhost

### ISSUE THREAD

**Issue by Aman7080** [kjmczk/nextjs-nft-mint-dapp#3]
Can you help me to solve this error ?
Getting this error when Dapp run in browser on localhost also I am not being able to run the test on polygon mumbai testnet.

1 of 1 unhandled error

Unhandled Runtime Error
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.5.0)

Call Stack
Logger.makeError
node_modules\@ethersproject\logger\lib.esm\index.js (185:0)
Logger.throwError
node_modules\@ethersproject\logger\lib.esm\index.js (194:0)
JsonRpcProvider.eval
node_modules\@ethersproject\providers\lib.esm\json-rpc-provider.js (357:0)
Generator.throw
<anonymous>
rejected
node_modules\@ethersproject\providers\lib.esm\json-rpc-provider.js (6:41)

**Comment by kjmczk** [comment]
Did you edit the `.env.development` file? It is for **Rinkeby** by default, so you need to edit it for **Mumbai**.

**Comment by Aman7080** [comment]
I am also getting this error for Rinkeby
