### ISSUE TITLE
can't resolve 'react-blockies'

### ISSUE THREAD

**Issue by bernycat** [kjmczk/nextjs-nft-mint-dapp#4]
Can you tell me how to resolve this?

            ./components/Header.tsx:5:0
            Module not found: Can't resolve 'react-blockies'
              3 | import { useEffect } from 'react';
              4 | import { useWeb3React } from '@web3-react/core';
            > 5 | import Blockies from 'react-blockies';
              6 | import { FaTwitter, FaDiscord, FaShip } from 'react-icons/fa';
              7 | 
              8 | import ConnectButton from './ConnectButton';
            
            Import trace for requested module:
            ./components/Layout.tsx
            ./pages/index.tsx
            
            https://nextjs.org/docs/messages/module-not-found

I cloned the most recent in which react-blockies was removed from the package.json and package-lock.json, but I get this error. 
Not sure if this was the right thing to do, but I was able to get it to run by commenting out line 5 in the header file:

// import Blockies from 'react-blockies';

**Comment by kjmczk** [comment]
I forgot to update the Header component. I just updated it, so please clone the app again.
