### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by devbewill** [kjmczk/nextjs-nft-mint-dapp#6]
Hi and thanks for your works!
Can u help me with tihs exception?
`Unhandled Runtime Error
Error: missing revert data in call exception (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":44,\"error\":{\"code\":-32000,\"message\":\"execution [reverted\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x03165fa1c28567d03bb17e0653d112b646350512\",\"data\":\"0x18160ddd\"},\"latest\"],\"id\":44,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rpc-mumbai.maticvigil.com/"},](http://localhost:3000/reverted/%22%7D%7D%22,%22error%22:%7B%22code%22:-32000%7D,%22requestBody%22:%22%7B/%22method/%22:/%22eth_call/%22,/%22params/%22:[%7B/%22to/%22:/%220x03165fa1c28567d03bb17e0653d112b646350512/%22,/%22data/%22:/%220x18160ddd/%22%7D,/%22latest/%22],/%22id/%22:44,/%22jsonrpc/%22:/%222.0/%22%7D%22,%22requestMethod%22:%22POST%22,%22url%22:%22https://rpc-mumbai.maticvigil.com/%22%7D,) data="0x", code=CALL_EXCEPTION, version=providers/5.5.0)`

i dont understand how to debug this error :(

**Comment by kjmczk** [comment]
It looks like an RPC error. Try changing the RPC URL for Mumbai to `https://rpc-mumbai.matic.today`. If it doesn't work, please clone the current version of the dApp and try again.

**Comment by devbewill** [comment]
Deleted, cloned again, changed variables in env.development, added my ABI but same results ;(
Ty for support man

**Comment by kjmczk** [comment]
hmm... I don't see that error on my PC. When does the error occur?

**Comment by devbewill** [comment]
When i rum NPM RUN START..
I can see the site correctly and can mint too bit the error persist, sane
results in the RInkeby too.


Il giorno mar 8 mar 2022 alle 01:04 Koji Mochizuki ***@***.***>
ha scritto:

**Comment by kjmczk** [comment]
I don't get the error on my PC when I run either `npm run dev` or `npm run build` & `npm run start`. There should be a problem with your settings.

Check again if the configs in the `.env.development`, `.env.production`, and `utils/constants.ts` files are correct. Also, make sure that the network settings registered in your wallet are correct.
